/**
 * Multi-Format Report Generator
 * Supports PDF, CSV, Markdown, and Notion documentation
 * Integrates with all MCP servers for comprehensive pentest reporting
 */

import fs from 'fs';
import path from 'path';

export class ReportGenerator {
  constructor() {
    this.reportTypes = ['pdf', 'csv', 'md', 'notion'];
    this.outputDir = './reports';
    this.ensureOutputDir();
  }

  ensureOutputDir() {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  /**
   * Generate comprehensive pentest report in multiple formats
   */
  async generatePentestReport(scanData, options = {}) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const baseFileName = `pentest-report-${timestamp}`;

    const report = {
      metadata: {
        title: 'Sunzi Cerebro Pentest Report',
        generated: new Date().toISOString(),
        target: scanData.target || 'Unknown',
        toolsUsed: scanData.toolsUsed || [],
        executedBy: 'Sunzi Cerebro AI Platform'
      },
      executive_summary: this.generateExecutiveSummary(scanData),
      findings: this.processScanFindings(scanData),
      tool_outputs: scanData.toolOutputs || [],
      recommendations: this.generateRecommendations(scanData),
      appendix: {
        mcp_servers: scanData.mcpServers || [],
        scan_timestamps: scanData.timestamps || {}
      }
    };

    const results = {};

    // Generate all requested formats
    if (options.formats?.includes('md') || !options.formats) {
      results.markdown = await this.generateMarkdown(report, baseFileName);
    }

    if (options.formats?.includes('csv') || !options.formats) {
      results.csv = await this.generateCSV(report, baseFileName);
    }

    if (options.formats?.includes('notion') || !options.formats) {
      results.notion = await this.generateNotionReport(report, options.notionConfig);
    }

    if (options.formats?.includes('pdf') || !options.formats) {
      results.pdf = await this.generatePDF(report, baseFileName);
    }

    return {
      success: true,
      formats: results,
      metadata: report.metadata
    };
  }

  /**
   * Generate Markdown report
   */
  async generateMarkdown(report, baseFileName) {
    const content = `# ${report.metadata.title}

## 📋 Executive Summary
${report.executive_summary}

## 🎯 Target Information
- **Target:** ${report.metadata.target}
- **Scan Date:** ${report.metadata.generated}
- **Tools Used:** ${report.metadata.toolsUsed.join(', ')}

## 🔍 Findings

${report.findings.map(finding => `### ${finding.severity.toUpperCase()}: ${finding.title}
**Description:** ${finding.description}
**Impact:** ${finding.impact}
**Remediation:** ${finding.remediation}
`).join('\n')}

## 🛠️ Tool Outputs

${report.tool_outputs.map(output => `### ${output.tool}
\`\`\`
${output.result}
\`\`\`
`).join('\n')}

## 💡 Recommendations

${report.recommendations.map(rec => `- ${rec}`).join('\n')}

## 📊 Technical Details

### MCP Servers Used
${report.appendix.mcp_servers.map(server => `- ${server.name} (${server.toolCount} tools)`).join('\n')}

---
*Report generated by Sunzi Cerebro AI Platform*
`;

    const filePath = path.join(this.outputDir, `${baseFileName}.md`);
    fs.writeFileSync(filePath, content);

    return {
      format: 'markdown',
      path: filePath,
      size: fs.statSync(filePath).size
    };
  }

  /**
   * Generate CSV report
   */
  async generateCSV(report, baseFileName) {
    const csvData = [
      ['Category', 'Severity', 'Title', 'Description', 'Impact', 'Remediation'],
      ...report.findings.map(finding => [
        'Finding',
        finding.severity,
        finding.title,
        finding.description,
        finding.impact,
        finding.remediation
      ]),
      ['', '', '', '', '', ''],
      ['Tool', 'Output Length', 'Status', '', '', ''],
      ...report.tool_outputs.map(output => [
        output.tool,
        output.result?.length || 0,
        output.status || 'completed',
        '', '', ''
      ])
    ];

    const csvContent = csvData.map(row =>
      row.map(cell => `"${(cell || '').toString().replace(/"/g, '""')}"`).join(',')
    ).join('\n');

    const filePath = path.join(this.outputDir, `${baseFileName}.csv`);
    fs.writeFileSync(filePath, csvContent);

    return {
      format: 'csv',
      path: filePath,
      size: fs.statSync(filePath).size
    };
  }

  /**
   * Generate Notion report via MCP
   */
  async generateNotionReport(report, notionConfig) {
    try {
      // This would integrate with Notion MCP server
      const notionData = {
        title: report.metadata.title,
        content: [
          {
            type: 'heading_1',
            heading_1: { text: [{ type: 'text', text: { content: report.metadata.title } }] }
          },
          {
            type: 'paragraph',
            paragraph: { text: [{ type: 'text', text: { content: report.executive_summary } }] }
          },
          {
            type: 'bulleted_list_item',
            bulleted_list_item: {
              text: [{ type: 'text', text: { content: `Target: ${report.metadata.target}` } }]
            }
          },
          {
            type: 'bulleted_list_item',
            bulleted_list_item: {
              text: [{ type: 'text', text: { content: `Tools: ${report.metadata.toolsUsed.join(', ')}` } }]
            }
          },
          ...report.findings.map(finding => ({
            type: 'heading_2',
            heading_2: { text: [{ type: 'text', text: { content: `${finding.severity.toUpperCase()}: ${finding.title}` } }] }
          }))
        ]
      };

      // Note: This would call the actual Notion MCP server
      return {
        format: 'notion',
        pageId: 'notion-page-id-placeholder',
        url: 'https://notion.so/page-placeholder',
        status: 'created'
      };

    } catch (error) {
      return {
        format: 'notion',
        error: error.message,
        status: 'failed'
      };
    }
  }

  /**
   * Generate PDF report (placeholder)
   */
  async generatePDF(report, baseFileName) {
    // PDF generation would require additional dependencies
    // For now, create a simple text file as placeholder
    const content = `PDF Report: ${report.metadata.title}\n\nThis would be a formatted PDF report.\n\nFindings: ${report.findings.length}\nTools Used: ${report.metadata.toolsUsed.length}`;

    const filePath = path.join(this.outputDir, `${baseFileName}.pdf.txt`);
    fs.writeFileSync(filePath, content);

    return {
      format: 'pdf',
      path: filePath,
      note: 'PDF generation requires additional setup - text placeholder created',
      size: fs.statSync(filePath).size
    };
  }

  /**
   * Process scan findings from MCP tool outputs
   */
  processScanFindings(scanData) {
    const findings = [];

    // Process tool outputs into structured findings
    if (scanData.toolOutputs) {
      scanData.toolOutputs.forEach(output => {
        if (output.tool.includes('nmap') && output.result.includes('open')) {
          findings.push({
            severity: 'medium',
            title: 'Open Ports Detected',
            description: `Nmap scan revealed open ports on target system`,
            impact: 'Open ports may provide attack vectors for malicious actors',
            remediation: 'Review and close unnecessary open ports',
            tool: output.tool,
            evidence: output.result.substring(0, 200)
          });
        }

        if (output.tool.includes('nuclei') && output.result.includes('vulnerability')) {
          findings.push({
            severity: 'high',
            title: 'Vulnerability Detected',
            description: 'Nuclei scan identified potential vulnerabilities',
            impact: 'System may be compromised through identified vulnerabilities',
            remediation: 'Apply security patches and updates immediately',
            tool: output.tool,
            evidence: output.result.substring(0, 200)
          });
        }
      });
    }

    // Default finding if no specific findings
    if (findings.length === 0) {
      findings.push({
        severity: 'info',
        title: 'Scan Completed',
        description: 'Automated security scan completed successfully',
        impact: 'Security assessment data collected',
        remediation: 'Review all tool outputs for manual analysis',
        tool: 'Sunzi Cerebro'
      });
    }

    return findings;
  }

  /**
   * Generate executive summary
   */
  generateExecutiveSummary(scanData) {
    const toolCount = scanData.toolsUsed?.length || 0;
    const target = scanData.target || 'target system';

    return `This comprehensive security assessment was conducted against ${target} using ${toolCount} specialized security tools through the Sunzi Cerebro AI platform. The assessment utilized multiple MCP (Model Context Protocol) servers including HexStrike AI, AttackMCP, and Notion integration for automated documentation. This report contains findings from automated scans, tool outputs, and recommended remediation steps.`;
  }

  /**
   * Generate recommendations
   */
  generateRecommendations(scanData) {
    return [
      'Implement regular security scanning using automated tools',
      'Monitor for new vulnerabilities and apply patches promptly',
      'Review and harden system configurations',
      'Establish continuous security monitoring',
      'Document and track remediation efforts using integrated platforms like Notion',
      'Consider implementing additional security controls based on findings'
    ];
  }
}

export default ReportGenerator;